# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Gather Ansible facts
  ansible.builtin.gather_facts:

- name: Include distribution vars
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}/main.yml"

- name: Include distribution release specific vars
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.yml"

- name: Install distribution packages
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}/packages-install.yml"

- name: Install the additional distribution release-specific Open Enclave prerequisites APT packages
  ansible.builtin.apt:
    name: "{{ apt_distribution_packages }}"
    state: latest
    update_cache: yes
    install_recommends: no
  when:
    - apt_distribution_packages is defined
    - apt_distribution_packages | length > 0

- name: Setup lvi dependencies
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}/lvi-setup.yml"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install CMake 3.13.1
  ansible.builtin.unarchive:
    src: https://cmake.org/files/v3.13/cmake-3.13.1-Linux-x86_64.tar.gz
    dest: "{{ cmake_prefix }}"
    remote_src: yes
  retries: 10
  delay: 10
  register: result
  until: result is success

- name: Create CMake symbolic links
  ansible.builtin.file:
    src: "{{ cmake_prefix }}/cmake-3.13.1-Linux-x86_64/bin/{{ item }}"
    dest: "{{ cmake_prefix }}/bin/{{ item }}"
    force: yes
    state: link
  with_items:
    - ccmake
    - cmake
    - cpack
    - ctest

- name: Download libssl1.1 Debian package
  ansible.builtin.get_url:
    url: "{{ ssl_package_url }}"
    dest: "{{ package_dest_path }}"
    checksum: "sha256:5ee003b8cb132a05e05a01f313c50d3d1fa90d4503bd45daa2a1d672ea73a6c1"
  register: ssl_download
  until: ssl_download is success
  retries: 3

- name: Install libssl1.1 on Jammy
  command: "dpkg -i {{ ssl_download.dest }}"
  when: not ssl_download.failed|bool and
        ansible_distribution_release == 'jammy'

- name: Download Azure-DCAP-Client
  ansible.builtin.get_url:
    url: "{{ dcap_package_url }}"
    dest: "{{ package_dest_path }}"
    checksum: "sha256:2fd26633ef0d8e279353a43a65779fb38d95fbfe43f4c934fbee3938756deddc"
  register: azdcap_download
  until: azdcap_download is success
  retries: 3

- name: Install Azure-DCAP-Client on Jammy
  command: "dpkg -i {{ azdcap_download.dest }}"
  when: not azdcap_download.failed|bool and
        ansible_distribution_release == 'jammy'
