# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

version: 2.0
jobs:

  #========Build-Test==========# 

  # SGX1 | Debug 
  build-test-sgx1-debug:
    docker:
      - image: oeciteam/oetools:1.0.0
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-Debug
          command:  |
            ./scripts/pre-commit &&
            ./scripts/build-testall 

  # SGX1 | RelWithDebInfo
  build-test-sgx1-relwithdebinfo:
    docker:
      - image: oeciteam/oetools:1.0.0
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run: 
          name: SGX1-RelWithDebInfo
          command:  |
             ./scripts/pre-commit &&
             ./scripts/build-testall -p SGX1 -b RelWithDebInfo
  
  # SGX1 | Release
  build-test-sgx1-release:
    docker:
      - image: oeciteam/oetools:1.0.0
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run: 
          name: SGX1-Release
          command:  |
             ./scripts/pre-commit &&
             ./scripts/build-testall -p SGX1 -b Release
             
  # SGX1-FLC | Debug 
  build-test-sgx1-flc-debug:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-FLC-Debug
          command:  |
             apt-get update &&
             apt-get install -y sudo &&
             sudo ./scripts/install-prereqs &&
             apt-get install -y libssl-dev &&
             #wget https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz &&
             #tar xf cmake-3.11.4-Linux-x86_64.tar.gz &&
             ./scripts/pre-commit &&
             sudo make -C prereqs USE_LIBSGX=1 NODOWNLOAD=1
             ls -la  ~/Microsoft-OE/prereqs/ngsa
             mkdir build &&
             cd build &&
             cmake .. -DUSE_LIBSGX=1 &&
             make &&
             OE_SIMULATION=1 ctest
             #./scripts/build-testall -p SGX1-FLC -b Debug

  # SGX1-FLC | RelWithDebInfo
  build-test-sgx1-flc-relwithdebinfo:
    docker:
      - image: oeciteam/oetools:1.0.0
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-FLC-RelWithDebInfo
          command:  |
             ./scripts/pre-commit &&
             ./scripts/build-testall -p SGX1-FLC -b RelWithDebInfo

  # SGX1-FLC | Release 
  build-test-sgx1-flc-release:
    docker:
      - image: oeciteam/oetools:1.0.0
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-FLC-Release
          command:  |
             ./scripts/pre-commit &&
             ./scripts/build-testall -p SGX1-FLC -b Release
             
workflows:
  version: 2
  build-test:
    jobs:                
      #  1. sgx1-debug((build-test))
      #- build-test-sgx1-debug
            
      # 2.  sgx1-relwithdebinfo(build-test)     
      # - build-test-sgx1-relwithdebinfo
            
      # 3.  sgx1-release(build-test)    
      # - build-test-sgx1-release
            
      # 4.  sgx1-flc-debug(build-test)
      - build-test-sgx1-flc-debug
            
      # 5.  sgx1-flc-relwithdebinfo(build-test)  
      # - build-test-sgx1-flc-relwithdebinfo
            
      # 6.  sgx1-flc-release(build-test)    
      # - build-test-sgx1-flc-release
