# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# Optimized version using 4 main jobs: 2 for debug and 2 for optimized builds

version: 2.0
jobs:
  # Pre-commit test - check license and formatting info
  pre-commit-test:
    docker:
      - image: oeciteam/oetools:1.2
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      - run:
          name: Pre-Commit Test
          command:  |
            ./scripts/pre-commit 

  #========Build-Test==========# 

  # SGX1 | Debug 
  ci-test-sgx1-debug:
    docker:
      - image: oeciteam/oetools:1.2
    working_directory: ~/Microsoft-OE
    filters:
      branches:
       only:
         - ci-work
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-Debug
          command:  |
            ./scripts/build-testall 

  # SGX1 | Optimized
  ci-test-sgx1-optimized:
    docker:
      - image: oeciteam/oetools:1.2
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run: 
          name: SGX1-Optimized
          command:  |
             ./scripts/build-testall -p SGX1 -b RelWithDebInfo &&
             rm -rf ./build  &&
             ./scripts/build-testall -p SGX1 -b Release
                         
  # SGX1-FLC | Debug 
  ci-test-sgx1-flc-debug:
    docker:
      - image: oeciteam/oetools:1.2
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-FLC-Debug
          command:  |
              apt-get update &&
              ./scripts/build-testall -p SGX1FLC -b Debug
            
  # SGX1-FLC | Optimized
  ci-test-sgx1-flc-optimized:
    docker:
      - image: oeciteam/oetools:1.2
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-FLC-Optimized
          command:  |
             ./scripts/build-testall -p SGX1FLC -b RelWithDebInfo &&
             rm -rf ./build &&
             ./scripts/build-testall -p SGX1FLC -b Release
             
workflows:
  version: 2
  ci-test:
    jobs:
      # 1. Pre-Commit test
      - pre-commit-test
      
      # 2. sgx1-debug(ci-test)
      - ci-test-sgx1-debug:
          requires:
            - pre-commit-test
            
      # 3. sgx1-optimized(ci-test)     
      - ci-test-sgx1-optimized:
          requires:
            - pre-commit-test
            
      # 4.  sgx1-flc-debug(ci-test)
      - ci-test-sgx1-flc-debug:
          requires:
            - pre-commit-test
            
      # 5.  sgx1-flc-optimized(ci-test)  
      - ci-test-sgx1-flc-optimized:
          requires:
            - pre-commit-test

