# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

version: 2.0
jobs:

  #========Build-Test==========# 

  # SGX1 | Debug 
  build-test-sgx1-debug:
    docker:
      - image: oeciteam/oetools:1.0.0
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-Debug
          command:  |
            mkdir build &&
            cd build &&
            cmake .. &&
            make &&
            OE_SIMULATION=1 ctest
             
  # SGX1 | RelWithDebInfo
  build-test-sgx1-relwithdebinfo:
    docker:
      - image: oeciteam/oetools:1.0.0
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run: 
          name: SGX1-RelWithDebInfo
          command:  |
            mkdir build &&
            cd build &&
            cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo &&
            make &&
            OE_SIMULATION=1 ctest
            
    # SGX1 | Release
  build-test-sgx1-release:
    docker:
      - image: oeciteam/oetools:1.0.0
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run: 
          name: SGX1-Release
          command:  |
            mkdir build &&
            cd build &&
            cmake .. -DCMAKE_BUILD_TYPE=Release &&
            make &&
            OE_SIMULATION=1 ctest
             
  # SGX1-FLC | Debug 
  build-test-sgx1-flc-debug:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-FLC-Debug
          command:  |
             apt-get update &&
             apt-get install -y sudo &&
             apt-get install -y git &&
             sudo ./scripts/install-prereqs &&
             apt-get install -y libssl-dev &&
             ./scripts/pre-commit &&
             sudo ./scripts/build-testall -p SGX1-FLC -b Release
            
  # SGX1-FLC | RelWithDebInfo
  build-test-sgx1-flc-relwithdebinfo:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-FLC-RelWithDebInfo
          command:  |
             apt-get update &&
             apt-get install -y sudo &&
             apt-get install -y git &&
             sudo ./scripts/install-prereqs &&
             apt-get install -y libssl-dev &&
             ./scripts/pre-commit &&
             sudo ./scripts/build-testall -p SGX1-FLC -b RelWithDebInfo

  # SGX1-FLC | Release 
  build-test-sgx1-flc-release:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-FLC-Release
          command:  |
             apt-get update &&
             apt-get install -y sudo &&
             apt-get install -y git &&
             sudo ./scripts/install-prereqs &&
             apt-get install -y libssl-dev &&
             ./scripts/pre-commit &&
             sudo ./scripts/build-testall -p SGX1-FLC -b Release
             
workflows:
  version: 2
  build-test:
    jobs:                
      #  1. sgx1-debug((build-test))
       # - build-test-sgx1-debug
            
      # 2.  sgx1-relwithdebinfo(build-test)     
       # - build-test-sgx1-relwithdebinfo
            
      # 3.  sgx1-release(build-test)    
       #- build-test-sgx1-release
            
      # 4.  sgx1-flc-debug(build-test)
       - build-test-sgx1-flc-debug
            
      # 5.  sgx1-flc-relwithdebinfo(build-test)  
       #- build-test-sgx1-flc-relwithdebinfo
            
      # 6.  sgx1-flc-release(build-test)    
       #- build-test-sgx1-flc-release
