# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

version: 2.0
jobs:

  #========Build-Test==========# 

  # SGX1 | Debug 
  sgx1-build-test:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-Debug-RelWithDebInfo
          command:  |
             apt-get update &&
             apt-get install -y sudo &&
             apt-get install -y git &&
             sudo ./scripts/install-prereqs &&
             apt-get install -y libssl-dev && 
             ./scripts/pre-commit &&
             mkdir build &&
             cd build &&
             echo Starting SGX1-Debug Build and Test Configuration -------------------------
             echo Starting SGX1-Debug Building ...
             cmake .. &&
             make &&
             echo Starting SGX1-Debug Testing ...
             OE_SIMULATION=1 ctest 
             echo Completed SGX1-Debug Test -------------------------
             echo Starting SGX1-RelWithDebInfo Build and Test Configuration -------------------------
             make clean
             echo Starting SGX1-RelWithDebInfo Building ...
             cmake .. -DCMAKE_BUILD_TYPE=relwithdebinfo &&
             make
             echo Starting SGX1-Debug Testing ...
             OE_SIMULATION=1 ctest 
             echo Completed SGX1-Debug Test -------------------------
             
  # SGX1-FLC | Debug 
  build-test-sgx1-flc-debug:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-FLC-Debug
          command:  |
             export SHELL=/bin/bash &&
             export shell=/bin/bash &&
             apt-get update &&
             apt-get install -y sudo &&
             apt-get install -y git &&
             ./scripts/pre-commit &&
             sudo ./scripts/build-testall -p SGX1-FLC -b Debug
             
workflows:
  version: 2
  build-test:
    jobs:                
      #  1. sgx1((build-test))
      # - sgx1-build-test
         
            
      # 2.  sgx1-flc(build-test)
       - build-test-sgx1-flc-debug
           
