# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

version: 2.0
jobs:

  #========Build-Test-Install==========# 

  # SGX1 | Debug 
  build-test-install-sgx1-debug:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build, Test and Install
      - run:
          name: SGX1-Debug
          command:  |
             export SHELL=/bin/bash &&
             export shell=/bin/bash &&
             apt-get update &&
             apt-get install -y sudo &&
             apt-get install -y git &&
             /bin/bash sudo ./scripts/pre-commit &&
             /bin/bash sudo ./scripts/build-testall
              
workflows:
  version: 2
  build-test-install:
    jobs:      
      #  1. sgx1-debug((build-test-install))
      - build-test-install-sgx1-debug
            
