# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

version: 2.0
jobs:

  #========Build-Test==========# 

  # SGX1 | Debug 
  build-test-sgx1-flc-debug:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build and Test
      - run:
          name: SGX1-FLC-Debug
          command:  |
             apt-get update &&
             apt-get install -y sudo &&
             apt-get install -y git &&
             sudo ./scripts/install-prereqs &&
             apt-get install -y libssl-dev &&
             ./scripts/pre-commit &&
             sudo ./scripts/build-testall -p SGX1-FLC -b Debug
            
workflows:
  version: 2
  build-test:
    jobs:      
      #  1. sgx1-flc-debug((build-test))
      - build-test-sgx1-flc-debug
            
      
