version: 2.0
jobs:

  #========Build-Test-Install==========# 

  # SGX1 | Debug 
  build-test-install-sgx1-debug:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build, Test and Install
      - run:
          name: SGX1-Debug
          command:  |
             apt-get install -y sudo &&
          # Add options later after fls-script is ready, like execute type etc.
             sudo sh ./scripts/fls-script     
  
  # SGX1 | RelWithDebug
  build-test-install-sgx1-relwithdebug:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build, Test and Install
      - run: 
          name: SGX1-RelWithDebInfo
          command:  |
             apt-get install -y sudo &&
          # Add options later after fls-script is ready, like execute type etc.
             sudo sh ./scripts/fls-script 

  # SGX1 | Release
  build-test-install-sgx1-release:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build, Test and Install
      - run: 
          name: SGX1-Release
          command:  |
             apt-get install -y sudo &&
         # Add options later after fls-script is ready, like execute type etc.
             sudo sh ./scripts/fls-script 
             
  # SGX1-FLS | Debug 
  build-test-install-sgx1-fls-debug:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build, Test and Install
      - run: 
          name: SGX1-FLS-Debug
          command:  |
             apt-get install -y sudo &&
          # Add options later after fls-script is ready, like execute type etc.
             sudo sh ./scripts/fls-script 

  # SGX1-FLS | RelWithDebug
  build-test-install-sgx1-fls-relwithdebug:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build, Test and Install
      - run: 
          name: SGX1--FLS-RelWithDebInfo
          command:  |
             apt-get install -y sudo &&
          # Add options later after fls-script is ready, like execute type etc.
             sudo sh ./scripts/fls-script 
             
  # SGX1-FLS | Release
  build-test-install-sgx1-fls-release:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/Microsoft-OE
    steps:
      - checkout
      # Build, Test and Install
      - run:   
          name: SGX1-FLS-Release
          command:  |
             apt-get install -y sudo &&
          # Add options later after fls-script is ready, like execute type etc.
             sudo sh ./scripts/fls-script 
             
workflows:
  version: 2
  build-test-install:
    jobs:      
      #  1. sgx1-debug((build-test-install))
      - build-test-install-sgx1-debug
            
      # 2.  sgx1-relwithdeb(build-test-install)     
      - build-test-install-sgx1-relwithdebug
            
      # 3.  sgx1-release(build-test-install)    
      - build-test-install-sgx1-release
            
      # 4.  sgx1-fls-debug(build-test-install)
      - build-test-install-sgx1-fls-debug
            
      # 5.  sgx1-fls-relwithdebug(build-test-install)  
      - build-test-install-sgx1-fls-relwithdebug
            
      # 6.  sgx1-fls-release(build-test-install)    
      - build-test-install-sgx1-fls-release