# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

# This installs Hashicorp Packer on Ubuntu
---

- name: Add Hashicorp Repository
  ansible.builtin.include_role:
    name: linux/common
    tasks_from: apt-repo.yml
  vars:
    apt_key_url: "https://apt.releases.hashicorp.com/gpg"
    apt_repository: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"

- name: Install Packer
  ansible.builtin.apt:
    name: packer
    state: latest
    update_cache: yes
    install_recommends: no
