# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
tmp_dir: "C:\\Windows\\Temp"
shellcheck_dest: "C:\\Program Files\\shellcheck"
jenkins_agent_root_dir: "C:/Jenkins"
servicewrapper_url: "https://github.com/cloudbase/OpenStackService/releases/download/v0.1/service-wrapper-sdk10-x64.zip"
openjdk_url: "https://aka.ms/download-jdk/microsoft-jdk-11.0.15-windows-x64.msi"

validation_binaries:
  - "C:\\Program Files\\Microsoft\\jdk-11.0.15.10-hotspot\\bin\\java.exe"
