# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Include distribution vars
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}/main.yml"

- name: Add Microsoft Repository
  ansible.builtin.include_role:
    name: linux/common
    tasks_from: apt-repo.yml
  vars:
    apt_key_url: "https://packages.microsoft.com/keys/microsoft.asc"
    apt_repository: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod {{ ansible_distribution_release }} main"

- name: Install the official Azure-DCAP-Client APT package
  ansible.builtin.apt:
    name: "az-dcap-client={{ az_dcap_client_version }}"
    state: present
    update_cache: yes
  # az-dcap-client is not available for Ubuntu 22.04
  when: ansible_distribution_release != 'jammy'

- name: Download Azure-DCAP-Client
  ansible.builtin.get_url:
    url: "{{ package_url }}"
    dest: "{{ package_dest_path }}"
    checksum: "sha256:2fd26633ef0d8e279353a43a65779fb38d95fbfe43f4c934fbee3938756deddc"
  register: azdcap_download
  until: azdcap_download is success
  retries: 3

- name: Install Azure-DCAP-Client on Jammy
  command: "dpkg -i {{ azdcap_download.dest }}"
  when: not azdcap_download.failed|bool
