# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---

- name: Include vars
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Make sure that Jenkins home exists
  ansible.windows.win_file:
    path: "{{ jenkins_agent_root_dir }}"
    state: directory

- name: OpenJDK - Download
  ansible.windows.win_get_url:
    url: "{{ openjdk_url }}"
    dest: "{{ tmp_dir }}\\openjdk-windows-x64.msi"

- name: OpenJDK - Install
  ansible.builtin.raw: "msiexec /i {{ temp_dir }}\\openjdk-windows-x64.msi ADDLOCAL=FeatureMain,FeatureEnvironment,FeatureJarFileRunWith,FeatureJavaHome INSTALLDIR="C:\Program Files\Microsoft\" /quiet

- name: Configure Git in target image to enable merge/rebase actions - email
  ansible.windows.win_shell: |
    git config --system user.email '{{ ci_team_email }}'

- name: Configure Git in target image to enable merge/rebase actions - name
  ansible.windows.win_shell: |
    git config --system user.name '{{ ci_team_name }}'
