# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
- hosts: linux-agents
  any_errors_fatal: true
  become: yes
  tasks:
    - import_role:
        name: linux/openenclave
        tasks_from: environment-setup.yml

    - import_role:
        name: linux/intel
        tasks_from: sgx-driver.yml

    - import_role:
        name: linux/intel
        tasks_from: sgx-packages.yml

    - import_role:
        name: linux/az-dcap-client
        tasks_from: stable-install.yml

    - block:
      - import_role:
          name: common/jenkins-agent
          tasks_from: agent-provision.yml
        delegate_to: localhost
      become: no

    - name: Check if node_secret fact is defined
      fail: 
        msg: "The node_secret fact is not defined!"
      when: node_secret is undefined

    - import_role:
        name: linux/jenkins
        tasks_from: slave-setup.yml

    - import_role:
        name: linux/validation
        tasks_from: slave-validation.yml

- hosts: windows-agents
  any_errors_fatal: true
  tasks:
    - block:
      - import_role:
          name: common/jenkins-agent
          tasks_from: agent-provision.yml
        delegate_to: localhost
      become: no

    - name: Check if node_secret fact is defined
      fail:
        msg: "The node_secret fact is not defined!"
      when: node_secret is undefined

    - import_role:
        name: windows/jenkins
        tasks_from: slave-setup.yml

    - import_role:
        name: windows/validation
        tasks_from: slave-validation.yml
